export const SHRTR_LINK_SUBMIT_PENDING = 'SHRTR_LINK_SUBMIT_PENDING'
export const SHRTR_LINK_SUBMIT_SUCCESS = 'SHRTR_LINK_SUBIMT_SUCCESS'
export const SHRTR_LINK_SUBMIT_FAILED = 'SHRTR_LINK_SUBMIT_FAILED'
export const SHRTR_LINK_INVALID = 'SHRTR_LINK_INVALID'