export const SHRTR_LINK_CHANGED = 'SHRTR_LINK_CHANGED'
export const SHRTR_LINK_SUBMIT_PENDING = 'SHRTR_LINK_SUBMIT_PENDING'
export const SHRTR_LINK_SUBMIT_SUCCESS = 'SHRTR_LINK_SUBIMT_SUCCESS'
export const SHRTR_LINK_SUBIMT_FAILED = 'SHRTR_LINK_SUBMIT_FAILED'