export const SHRNK_LINK_SUBMIT_PENDING = 'SHRNK_LINK_SUBMIT_PENDING'
export const SHRNK_LINK_SUBMIT_SUCCESS = 'SHRNK_LINK_SUBIMT_SUCCESS'
export const SHRNK_LINK_SUBMIT_FAILED = 'SHRNK_LINK_SUBMIT_FAILED'
export const SHRNK_LINK_INVALID = 'SHRNK_LINK_INVALID'